# Railway Configuration for Full-Stack Auth App

# Backend Service
[[services]]
name = "auth-backend"
dockerfile = "Dockerfile"

[services.variables]
NODE_ENV = "production"
APP_ENV = "prod"
PORT = "3000"
HOST = "0.0.0.0"
JWT_SECRET = "${{JWT_SECRET}}"
JWT_EXPIRES_IN = "24h"
LOG_LEVEL = "info"
CLIENT_URL = "${{CLIENT_URL}}"
CORS_ORIGINS = "${{CLIENT_URL}}"

# Frontend Service  
[[services]]
name = "auth-frontend"
dockerfile = "client/Dockerfile"

[services.variables]
NODE_ENV = "production"
PORT = "80"

[services.build]
args = { API_URL = "${{API_URL}}", CLIENT_URL = "${{CLIENT_URL}}" }
