# Railway Configuration for Full-Stack Auth App
# Minimal configuration - environment variables set manually in Railway dashboard

# Backend Service
[[services]]
name = "auth"
dockerfile = "Dockerfile"
root = "."

# Frontend Service  
[[services]]
name = "auth-web"
dockerfile = "client/Dockerfile"
root = "."
