# Railway Configuration for Full-Stack Auth App

# Backend Service
[[services]]
name = "auth-backend"
source = "."
dockerfile = "Dockerfile"

[services.variables]
NODE_ENV = "production"
APP_ENV = "prod"
PORT = "3000"
HOST = "0.0.0.0"
JWT_SECRET = "your-super-secret-jwt-key-change-this-in-production"
JWT_EXPIRES_IN = "24h"
LOG_LEVEL = "info"

# Frontend Service
[[services]]
name = "auth-frontend"
source = "."
dockerfile = "client/Dockerfile"

[services.variables]
NODE_ENV = "production"
PORT = "80"
