[build]
builder = "dockerfile"

[deploy]
dockerfilePath = "Dockerfile"

[environments.production]
variables = [
  { name = "NODE_ENV", value = "production" },
  { name = "JWT_SECRET", value = "your-super-secret-jwt-key-change-this-in-production" }
]
